### PR TITLE
fix: Disable autonaming for iam/v1:OrganizationRole

### PR DESCRIPTION
**Pull request by alexstojda**
- Same issue as #209 which was fixed in #646

### CODE REVIEW

**Comment by alexstojda** [comment]
@viveklak hey! Since you authored #646 would you mind reviewing and merging this one? 

TIA

**Comment by mikhailshilkov** [comment]
Hi @alexstojda 

I'm sorry for a long silence... the change LGTM - could you please rebased on the latest to solve the changeling conflict? I'll merge the PR after that.

**Comment by alexstojda** [comment]
@mikhailshilkov rebased as requested

**Pull request merged**
