### PR TITLE
Update author input for automated PRs

### PR DESCRIPTION
**Pull request by jkisk**
Add input so pulumi-bot will be the author of automated PRs

### CODE REVIEW

**Review by jkodroff — APPROVED** [review]

**Comment by viveklak** [comment]
If we rerun, don’t we want the change to be cumulative - I.e keep the same branch? Just trying to understand the problem this causes.

**Comment by jkisk** [comment]
> If we rerun, don’t we want the change to be cumulative - I.e keep the same branch? Just trying to understand the problem this causes.

That's a good point actually, and I'm open to keeping the same branch name if that's better.  I'm not familiar enough with the process here to know if we would ever want to have access to the generated sdks from an unsuccessful run.

**Comment by viveklak** [comment]
> > If we rerun, don’t we want the change to be cumulative - I.e keep the same branch? Just trying to understand the problem this causes.
> 
> That's a good point actually, and I'm open to keeping the same branch name if that's better. I'm not familiar enough with the process here to know if we would ever want to have access to the generated sdks from an unsuccessful run.

I suppose if we needed to we could always replicate that locally? I think reducing the branch splay is a better option. I'd recommend removing the run_attempt for now but keep the author part?

**Review by viveklak — APPROVED** [review]
Change the PR title as well?

**Pull request merged**
