### PR TITLE
Fix link to guide

### LINKED ISSUE #250: README points to the classic provider's config
> Please refer to this quickstart guide for possible configuration options.

Points to the GCP provider which uses the `gcp:*` configuration scheme while we should point to `google-native:*`. Also, 

> Credentials configuration is compatible with the classic GCP provider.

isn't exactly right - we should point to the difference above.

### PR DESCRIPTION
**Pull request by danielrbradley**
Closes #250 

- Point to native guide rather than classic.
- Tidy up code blocks.

### CODE REVIEW

**Review by mikhailshilkov — APPROVED** [review]
This is great. FWIW, #250 has a second part to clarify that "Credentials configuration is compatible with the classic GCP provider." isn't exactly true: the keys should start with `google-native` instead of `gcp`. I suspect we have this problem in all `-native` providers.

**Comment by danielrbradley** [comment]
> "Credentials configuration is compatible with the classic GCP provider." isn't exactly true: the keys should start with `google-native` instead of `gcp`.

Just been looking at this and I think it's slightly misleading but technically true - the **credentials** are configured in exactly the same way as the classic providers - fetched from the associated CLI tool or environment variable. But the non-credentials configuration is different as it uses Pulumi's config which is then namespaced for the provider.

**Comment by danielrbradley** [comment]
@mikhailshilkov looking at the classic provider's readme - there's no information on this at all. You happy if I just remove the line completely to remove confusion?

**Comment by mikhailshilkov** [comment]
> Just been looking at this and I think it's slightly misleading but technically true - the credentials are configured in exactly the same way as the classic providers 

Ah, that's fair.

> But the non-credentials configuration is different as it uses Pulumi's config which is then namespaced for the provider.

Maybe we could add a sentence about this.

> Looking at the classic provider's readme - there's no information on this at all. You happy if I just remove the line completely to remove confusion?

I guess I'd rather keep it and clarify the statement. Using two providers at the same time is an important scenario that we want to highlight.

**Review by mikhailshilkov — APPROVED** [review]
LGTM

**Pull request merged**
