### PR TITLE
Add Java packages overrides to schema

### PR DESCRIPTION
**Pull request by pawelprazak**
Part of https://github.com/pulumi/pulumi-java/issues/381

### CODE REVIEW

**Comment by pawelprazak** [comment]
updated and rebased

**Review by viveklak — APPROVED** [review]

**Comment by viveklak** [comment]
@pawelprazak apologies for the delay. Could you resolve the CHANGELOG.md conflict? LGTM otherwise.

**Comment by mikhailshilkov** [comment]
It has to be added manually to each provider where overrides are needed. It's very similar to `csharpNamespaces` but we require them in fewer places because our defaults are closer to Java than to C#.

**Pull request merged**
