### PR TITLE
Refresh discovery docs

### PR DESCRIPTION
**Pull request by viveklak**

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
The build failure seems legit - do you know what happened?

**Comment by mikhailshilkov** [comment]
@viveklak Do you have capacity to finish this off or shall I take it over?

**Comment by viveklak** [comment]
> @viveklak Do you have capacity to finish this off or shall I take it over?

This was on my list. I will take care of it in the morning.

**Comment by mikhailshilkov** [comment]
Closing in favor of https://github.com/pulumi/pulumi-google-native/pull/151

**Pull request closed without merging**
